
---
#old version
---

# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!
# new version


#1 - create SA - my-super-sa
#2 - add role and bla bla bla
#3 - add serviceAccountName to pod and

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: example-sa
automountServiceAccountToken: false # you can add it to pod spec.automountServiceAccountToken:false

---
# kubectl create sa  my-super-sa

apiVersion: v1
kind: Pod
metadata:
  name: projected-token-example
spec:
  serviceAccountName: my-super-sa  # или другой service account
  containers:
    - name: demo
      image: busybox
      command: ["sleep", "3600"]
      volumeMounts:
        - name: projected-volume
          mountPath: /var/run/secrets/projected
          readOnly: true
  volumes:
    - name: projected-volume
      projected:
        sources:
          - serviceAccountToken: # Generate tokem without "create secret" with kubernetes.io/service-account.name
              path: token
              expirationSeconds: 3600


