apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-sleeper
  namespace: default
spec:
  securityContext:  # pod level - apply to all pod
    runAsUser: 1010
  containers:
    - command:
        - sleep
        - "4800"
      image: ubuntu
      name: ubuntu-sleeper

      securityContext: # container level - apply to current container
        capabilities:
          add: ["SYS_TIME"]