apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-all-egress
spec:
  podSelector:
    matchLabels:
      name: my_pod # apply only to my_pod
  egress:
    - {}   # if empty allow all
  policyTypes:
    - Egress

---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny-all-egress
spec:
  podSelector:
    matchLabels:
      name: my_pod # apply only to my_pod
  policyTypes:
    - Egress
  #
  #egress:  < - WITHOUT EGRESS, DENY ALL
  #  - { }  < - WITHOUT EGRESS, DENY ALL
  #

